include:
  - project: 'dev-ops/hebergement_web/templates/remote-ci-templates'
    ref: 'main'
    file: 'Auto-DevOps.gitlab-ci.yml'

default:
  tags: [coriolis-runner]

variables:
  TPL_IMAGE_BUILD_ARGS: "--build-arg HEADER_TOKEN=\"JOB-TOKEN: ${CI_JOB_TOKEN}\" --build-arg APP_VERSION=${CI_COMMIT_TAG} --build-arg APP_FILENAME=argo-decoder-${CI_COMMIT_TAG}.zip"

publish_docker_on_registry:
  extends: [.docker, .exists-dockerfile, .only-on-valid-tag]