include:
  - project: 'dev-ops/hebergement_web/templates/remote-ci-templates'
    ref: 'main'
    file: 'Auto-DevOps.gitlab-ci.yml'

default:
  tags: [coriolis-runner]

.only-on-tag:
  rules:
    - if: '$CI_COMMIT_TAG != null'

publish_docker_on_registry:
  # extends: [.docker-push-on-project-registry, .only-on-tag]
  extends: [.docker-push-on-project-registry]
  stage: publish
  variables:
    TPL_IMAGE_BUILD_ARGS: "--build-arg HEADER_TOKEN=JOB-TOKEN:${CI_JOB_TOKEN} --build-arg APP_VERSION=20240111 --build-arg APP_FILENAME=argo-decoder-20240111.zip"
